css done page working - upload file WIP
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Street-Art-Hunter pull request #18
Opened 2024-09-06 08:25 UTC by RosaBen

css done - page working- will work on upload file later

2024-09-06 08:40 UTC, RossAlex0 approved these changes
Good job :)

2024-09-06 09:00 UTC, kpeset requested changes

2024-09-06 09:00 UTC, kpeset commented on client/src/components/ProfileForm.jsx
> +          {fields.map((field) => (
Je ne suis pas très fan de boucler sur le formulaire. Dans un soucis de compréhension globale du formulaire, j'aimerais avoir tous les champs directement visible dans ProfileForm

2024-09-09 09:33 UTC, ChaMm17 approved these changes
Yes !

2024-09-09 09:56 UTC, kpeset approved these changes

2024-09-09 09:56 UTC, merged