Us02 galleries
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Street-Art-Hunter pull request #22
Opened 2024-09-10 14:02 UTC by Davido91390

2024-09-10 14:06 UTC, RossAlex0 approved these changes
Félicitations x2 !

2024-09-10 14:07 UTC, ChaMm17 approved these changes
Top !

2024-09-10 14:29 UTC, kpeset requested changes
Faire le filtre côté backend :)

2024-09-10 14:29 UTC, kpeset commented on client/src/pages/Gallery.jsx
> +  const [styleFilter, setStyleFilter] = useState();
On ne filtrera pas côté client, mais plutôt côté back.

2024-09-11 19:31 UTC, Davido91390 commented on client/src/pages/Gallery.jsx
> +  const [styleFilter, setStyleFilter] = useState();
C'est good c'est réglé

2024-09-12 08:55 UTC, RossAlex0 approved these changes
Nice 🔥

2024-09-12 12:24 UTC, kpeset requested changes

2024-09-12 12:24 UTC, kpeset commented on client/src/pages/Gallery.jsx
> +  const getArtworks = (toto) => {
toto ?

2024-09-12 12:37 UTC, kpeset approved these changes

2024-09-12 12:37 UTC, merged