Us01 user connection
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Street-Art-Hunter pull request #33
Opened 2024-09-18 12:50 UTC by ChaMm17

2024-09-18 13:15 UTC, Davido91390 approved these changes
Nice

2024-09-18 15:11 UTC, RossAlex0 approved these changes
Good

2024-09-18 15:44 UTC, kpeset requested changes

2024-09-18 15:44 UTC, kpeset commented on client/src/pages/Connection.jsx
> +  const emailRef = useRef();
Stocker les valeurs des inputs email et password dans un state.
Beaucoup mieux que les useRef !

2024-09-18 18:47 UTC, ChaMm17 commented on client/src/pages/Connection.jsx
> +  const emailRef = useRef();
Merci Kévin, les modifs sont faites.

2024-09-19 08:39 UTC, kpeset approved these changes

2024-09-19 08:39 UTC, merged