Us01 admin
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Street-Art-Hunter pull request #38
Opened 2024-09-23 14:49 UTC by Davido91390

2024-09-23 15:03 UTC, RossAlex0 approved these changes
Good 🔥

2024-09-24 13:34 UTC, ChaMm17 approved these changes
Nice !

2024-09-24 13:55 UTC, kpeset requested changes
Des incohérences dans ce code. Est-ce qu'il y a eu une aide extérieure du type IA ? ^^

2024-09-24 13:55 UTC, kpeset commented on server/database/models/ArtworkRepository.js
> +  async readAllByAdmin() {
Ici tu crée une fonction readAllByAdmin sans parametres

2024-09-24 13:55 UTC, kpeset commented on server/app/controllers/ArtworkActions.js
> +    const artworks = await tables.artwork.readAllByAdmin(artworkStyle);
Ici tu executes readAllbyAdmin avec argument

2024-09-24 14:10 UTC, kpeset approved these changes

2024-09-24 14:10 UTC, merged