Add function for delete profil
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Street-Art-Hunter pull request #39
Opened 2024-09-24 18:35 UTC by Davido91390

2024-09-24 19:05 UTC, CyrThoDev requested changes
vu ensemble - Quelques modifications à apporter

2024-09-24 19:05 UTC, CyrThoDev commented on client/src/pages/Profile.jsx
> +        window.alert("Votre profil a bien été supprimé");
Regarder comment afficher un toast plutôt qu'une alerte

2024-09-24 19:05 UTC, CyrThoDev commented on client/src/pages/Profile.jsx
> +  const sendCredential = (event) => {
Modifier le nom de la fonction pour qu'elle corresponde à la fonctionnalité effectuée (par exemple deleteUser...)

2024-09-25 09:27 UTC, RossAlex0 approved these changes
Perfect !

2024-09-25 09:29 UTC, ChaMm17 approved these changes
Top !

2024-09-25 09:49 UTC, kpeset approved these changes

2024-09-25 10:08 UTC, merged