Us01 path
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Street-Art-Hunter pull request #8
Opened 2024-09-03 14:58 UTC by RosaBen

added Edit and delete routes from BREAD for artworks, cities, favorites, styles, users,
schema.sql updated,
console info added for few routes

2024-09-03 15:05 UTC, Davido91390 approved these changes
Good job

2024-09-03 15:22 UTC, RossAlex0 approved these changes
Parfait 👍

2024-09-04 09:20 UTC, kpeset requested changes

2024-09-04 09:20 UTC, kpeset commented on server/database/schema.sql
> +    lat int NOT NULL,
INT ou DOUBLE finalement ?

2024-09-04 09:37 UTC, Davido91390 commented on server/database/schema.sql
> +    lat int NOT NULL,
On a mit double pour avoir aussi les décimales

2024-09-04 12:09 UTC, kpeset requested changes
Il manque les doubles pour lat et lon de artwork  dans le schema.sql

2024-09-04 12:30 UTC, kpeset approved these changes

2024-09-04 12:30 UTC, merged