:rocket: add map and marker for each artworks
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Street-Art-Hunter pull request #9
Opened 2024-09-03 15:32 UTC by ChaMm17

2024-09-03 15:34 UTC, RossAlex0 approved these changes
Nice 👌

2024-09-03 15:35 UTC, Davido91390 approved these changes
Nice

2024-09-04 09:22 UTC, kpeset requested changes

2024-09-04 09:22 UTC, kpeset commented on client/package.json
> +    "eslint-plugin-import": "^2.30.0",
C'est koé ?

2024-09-04 09:46 UTC, kpeset approved these changes
Parfait :) à optimiser avec le temps pour mettre la logique de la carte dans un composant

2024-09-04 09:46 UTC, merged